name: CI
on:
  [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm i
      working-directory: frontend
    - run: npm run build
      working-directory: frontend
    - run: mkdir -p target
    - run: mv index.html target/
    - run: mv assets target/assets
    - run: touch target/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: target
    - run: rm -r target
